mybatis:
  mapper-locations: classpath*:mappers/basic/**/*.xml
spring:
  datasource:
    #url: jdbc:mysql://localhost/test?autoReconnect=true
    #driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:log4jdbc:mysql://localhost:19002/basic?autoReconnect=true
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: basic
    password: 1234
logging:
  config: classpath:logback.xml
#logging:
#  level: 
#    com.spring.basic: debug
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
    