mybatis:
  mapper-locations: classpath*:mappers/basic/**/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost/test?autoReconnect=true
    driverClassName:  com.mysql.cj.jdbc.Driver
    username: root
    password: zaq12wsx